---
RecipeFormatVersion: "2020-01-25"
ComponentName: "com.maritime.inference"
ComponentVersion: "1.0.0"
ComponentDescription: "Maritime threat detection inference component"
ComponentPublisher: "Maritime ACPS"
ComponentConfiguration:
  DefaultConfiguration:
    ModelPath: "/greengrass/v2/packages/artifacts/com.maritime.inference/1.0.0/model.pt"
    InferenceInterval: 5
    ConfidenceThreshold: 0.7
    IoTTopic: "maritime/detections"
ComponentDependencies:
  aws.greengrass.Nucleus:
    VersionRequirement: ">=2.0.0"
Manifests:
  - Platform:
      os: linux
    Lifecycle:
      Install:
        RequiresPrivilege: false
        Script: |
          pip3 install torch torchvision onnxruntime paho-mqtt numpy
      Run:
        RequiresPrivilege: false
        Script: |
          python3 {artifacts:path}/inference_agent.py
    Artifacts:
      - URI: "s3://BUCKET_NAME/greengrass-components/maritime-inference/inference_agent.py"
      - URI: "s3://BUCKET_NAME/greengrass-components/maritime-inference/model.pt"